# Generated by Django 2.0.6 on 2018-06-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180625_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number_of_donated_books',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
