# Generated by Django 2.0.6 on 2018-06-28 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180625_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='borrowed_books',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reserved_books',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='book',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='person',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='book',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='person',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
