# Generated by Django 2.0.6 on 2018-07-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180706_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number_of_donated_books',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
