# Generated by Django 2.0.6 on 2018-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180707_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='penalty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
