# Generated by Django 2.0.6 on 2018-07-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180630_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.CharField(choices=[('P', 'Poem'), ('S', 'Story'), ('H', 'History'), ('M', 'Magazine'), ('B', 'Biography')], default='S', max_length=1),
        ),
    ]
