# Generated by Django 2.0.6 on 2018-07-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1),
        ),
        migrations.AddField(
            model_name='loan',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
    ]
